### ISSUE TITLE
Killing docker build breaks index building

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#118]
If the index is currently built and then canceled, it is broken.
For now: delete files at `swiss_TLM_api\index_cache`
Should be: automatically detect cancel and/or broken files, recreate them.

**Comment by wp99cp** [comment]
@maede97 I think this problem isn't solved yet.

If you use the index files in the zip and start an export with the provided GPX file, the swiss_TLM service crashes.

[reproducing_files.zip](https://github.com/cevi/automatic_walk-time_tables/files/10042542/reproducing_files.zip)

**Comment by maede97** [comment]
Can confirm that for this broken files, it does also crash on windows.
