### ISSUE TITLE
Improve CI: Force Check-Boxes to be Checked before Merging a PR

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#129]
@btemperli can you install the follwoing GitHub App?

- Task list completed see https://github.com/marketplace/task-list-completed

This allows us to enforce that all checkboxes are checked before a PR can be merged, e.g. useful to track manual tasks before deployment.

**Comment by btemperli** [comment]
Is installed. I have taken the liberty of installing this for all repositories, so that it can be used globally when needed.
