### ISSUE TITLE
Add Option to Delete POI

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#147]
Currently, the is no way to delete a POI after you created it.
There should be an easy way to delete a POI once you have created one.

See also #131

**Comment by carlobeltrame** [comment]
This was a highly requested feature in a course, independently by multiple participants using the tool.

**Comment by maede97** [comment]
I propose right click on an existing point should delete it.

**Comment by carlobeltrame** [comment]
Right click is not really a common and intuitive action on the web, and it is impossible to do on mobile devices. Instead I would recommend adding a trash button or three-dot-menu somewhere

**Comment by maede97** [comment]
Or click on an existing point to delete it.

**Comment by maede97** [comment]
Implemented in Version 4.1.0.
