### ISSUE TITLE
[Naming] Improve Naming

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#15]
Currently, the repo has the name "automatic_walk-time_tables". (mixed underscore and dashes).
I think we should stick to one of these two.

**Comment by wp99cp** [comment]
The thought behind this was that I would write walk-time with a dash. Therefore _automatic walk-time tables_ become _automatic_walk-time_tables_. But I can understand your comment, maybe we should change it.

**Comment by wp99cp** [comment]
Can we close this issue? Or should we update the repo name? @maede97 What's your opinion?

**Comment by maede97** [comment]
I don't care. :-)
