### ISSUE TITLE
GPXPy Error on Ubuntu 20.04

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#19]
Executing the current master branch runnable does not work on Ubuntu 20.4 Focal:

```
matthias:python_program(master) $ python3 main.py --gpx-file-name "./GPX/4-Tage-Hike 1.gpx" 
Traceback (most recent call last):
  File "main.py", line 52, in <module>
    generate_automated_walk_table(departure_date=args.departure_time,
  File "main.py", line 14, in generate_automated_walk_table
    raw_gpx_data = gpxpy.parse(gpx_file)
  File "/home/matthias/.local/lib/python3.8/site-packages/gpxpy/__init__.py", line 39, in parse
    return parser.parse(version)
  File "/home/matthias/.local/lib/python3.8/site-packages/gpxpy/parser.py", line 114, in parse
    mod_etree.register_namespace(prefix, URI.strip('"'))
  File "src/lxml/etree.pyx", line 185, in lxml.etree.register_namespace
  File "src/lxml/apihelpers.pxi", line 1755, in lxml.etree._uriValidOrRaise
ValueError: Invalid namespace URI 'http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd https://swisstopo-app.ch/xmlschemas/SwisstopoExtensions https://prod-static.swisstopo-app.ch/xmlschemas/SwisstopoExtensions.xsd'
```

**Comment by maede97** [comment]
It is the same GPX file I use for testing on windows and on my linux subsystem.
There it works.

**Comment by maede97** [comment]
It does also not work with a newly exported GPX file from the swisstopo app.

Also the URL provided (the swisstopo-app one) seems to be not valid?

**Comment by wp99cp** [comment]
I cannot reproduce the bug using WSL (Ubuntu 20, master https://github.com/cevi/automatic_walk-time_tables/commit/f5e412013e67242dfac8ee187045a9cfe2d8c166).

Can you upload your GPX file? Please also try the following GPX file: [Test_Walk_Swisstopo_App.zip](https://github.com/cevi/automatic_walk-time_tables/files/7469725/Test_Walk_Swisstopo_App.zip).

**Comment by maede97** [comment]
Both your GPX file as well as a newly created one don't work.
GPX files exported from the swissmobile app seem to work.

I think we should not fix this right now. Potentially this is a bug only targeting Ubuntu 20.04 focal (not as a subsystem) or rather something with this current setup. Adding `wont-fix` and closing this. But keep it in mind.
