### ISSUE TITLE
Remove Duplicate Testing

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#191]
After merging a PR to the master branch, the following actions run.

![image](https://github.com/cevi/automatic_walk-time_tables/assets/34008738/583cc69b-81c7-49a7-ac19-1cb5f8e97b4c)

It would be beneficial to eliminate the testing and development build action at this point. We have no intention of deploying a new version to dev.map.cevi.tools when committing to the master branch, and there is no necessity to test the application again. This is because any commits to the master branch must have passed through a PR, which will always include a testing step.

**Comment by wp99cp** [comment]
The dev build may be caused by the back merging to dev (I merged the latest version of master back to dev immediately after the original merge commit to master). Maybe here, the GitHub interface is misleading here?

The settings for the dev build are as follows: 
https://github.com/cevi/automatic_walk-time_tables/blob/a3d293a40f8995dcf23099320812afa0fe3dc763/.github/workflows/dev_build.yml#L3-L6

Anyway, for the testing, we can limit the triggers quite a bit... I propose to enable testing only for active PR and not for every commit in general. @maede97 do you think that is a good idea?
https://github.com/cevi/automatic_walk-time_tables/blob/a3d293a40f8995dcf23099320812afa0fe3dc763/.github/workflows/cypress.yml#L2-L5

**Comment by maede97** [comment]
Agree. Let's not waste github's computer power :-)
