### ISSUE TITLE
Computing Blatteinteilung locally

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#202]
Somewhere should be a SHP file (or somewhat similar) with the data.
https://www.geocat.ch/geonetwork/srv/ger/catalog.search#/metadata/78f00172-59ec-4b38-9106-cdddfb40e514

We should download this once, then use it locally instead of performing API requests.

**Comment by wp99cp** [comment]
Here you can find the data, I didn't find any other direct source:
- https://shop.swisstopo.admin.ch/de/api/geojson/814
- https://shop.swisstopo.admin.ch/de/api/geojson
