### ISSUE TITLE
Improve Logging

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#22]
Improve the log output of the applications. In some parts, logs are quite sophisticated (e.g. map download) whereas other parts are silent (e.g. elevation map creation). We can improve logging by adding the following logs: 

- [ ] Summary of passed command-line args
- [ ] Runtime info, as done for the map download
- [ ] Summary at the end. List created files and directory
- [ ] others...

In this process, we can also switch to [Logging facility for Python](https://docs.python.org/3/library/logging.html) right away.

**Comment by maede97** [comment]
If we finally implement #24, we could also show the log to the web user?

**Comment by wp99cp** [comment]
> If we finally implement #24, we could also show the log to the web user?

Yes, but only for the current export thread, not at the global level. Maybe just returning with an error message is enough for the end user.
