### ISSUE TITLE
Create Simple Webinterface

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#24]
# Create Simple Web Interface

In order to make the tool accessible to as many _Cevianer_ as possible, it should be available as a web service. This issue serves as an overview of transforming the script into a web service.

### PDF Export with `mapfish`
- [x] Create a custom docker image for the `mapfish` instance including our config files (done #23)
- [ ]  Host the docker container and setup GitHub Action

### Base Script: `python_program`
- [x] Implement basic functionality 
- [x] Improve logging #22

### Midelware: Backend
- [x] Create a Docker image running a flask server. The server has one endpoint accepting a GPX file, then triggers the `python_program`. The existing command-line arguments can be passed as query parameters. See https://github.com/wp99cp/eMeal_menuplanung/blob/e5173aaa1c8af12e9f1e72d35d8e1853e526aa0f/backend/pdf-export-module/script/app.py#L14-L21.
- [ ] Implement some sort of user authentication / query limits
- [ ]  Host the docker container and setup GitHub Action

### Frontend
- [x] Create a simple fronted: The end user should be able to upload a GPX FIle, make some settings for export and then click on a button "Erstellen". A ZIP file will be created and downloaded containing the created files.
- [ ] Host Frontend and setup GitHub Action

## Open for discussion

- #25 
- #26

- Other topics will follow for sure...

**Comment by maede97** [comment]
Maybe we should split the discussion points into multiple issues, in order to keep it clean & understandable?

**Comment by wp99cp** [comment]
> Maybe we should split the discussion points into multiple issues, in order to keep it clean & understandable? And then just link here to the discussion issues.

Done, at least for the discussion points. Todo's we will spill into issues, once we are working on them. E.g. #22.
