### ISSUE TITLE
URL of Webpage and Hosting

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#26]
In order to make the tool accessible to as many _Cevianer_ as possible, it should be available as a web service.  Should we buy a custom domain or should we use something like [map.cevi.tools](map.cevi.tools)?

**Comment by maede97** [comment]
I like map.cevi.tools, however, we could also use marschzeit.cevi.tools?
map.cevi.tools could maybe be used later for the current cevimap.ch?

**Comment by wp99cp** [comment]
Now #38 is close to release, we should discuss where to host it, which options do we have?

- Buy a vServer (e.g. hosted by Hosttech)
(-) Expensive
(+) Very flexible

- Use a Docker Hosting Service
(+) cheaper than vServer
(-) On most, you will pay per container

- Use Cloud Run (Google) or Amazon ECS
(+) even cheaper than docker host (runs only if a user is requesting the service)
(-) need some changes to the code (optimizing for cold starts)

**Comment by maede97** [comment]
@nchiapol are there options to host on the cevi server?

**Comment by wp99cp** [comment]
> @nchiapol are there options to host on the cevi server?

I don't know the specs of the cevi server, but at the moment, the resources needed for running our application are quite high. Especially memory consumption is quite high, as mapfish needs 1.2 GiB during idle state. We should consider tweaking some settings to lower them... On load, the memory consumption is roughly 200 MiB more for both mapfish and the backend container.

**Resources needed in idle state:**
```bash
CONTAINER ID   NAME                                        CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
4c39597e2633   automatic_walk-time_tables_webinterface_1   0.00%     16.55MiB / 30.97GiB   0.05%     61.3kB / 4.46MB   10.8MB / 8.19kB   17
ba363a07508c   automatic_walk-time_tables_backend_1        0.03%     280.4MiB / 30.97GiB   0.88%     19.1MB / 20.1MB   146MB / 49.2kB    4
9d7f82a8a6f2   automatic_walk-time_tables_mapfish_1        0.20%     1.268GiB / 30.97GiB   4.09%     34.7MB / 19.7MB   148MB / 36MB      164

**Comment by maede97** [comment]
Mapfish can be used as "running only when needed", right? The idea is to build the name and place index once, keep it stored and then have faster creation? But mapfish does not have to be running all the time.

**Comment by wp99cp** [comment]
> The idea is to build the name and place index once, keep it stored and then have faster creation?

If the docker container isn't running all the time, we clearly need to go that way. Otherwise, the current solution is fine, at least for the moment.

**Comment by wp99cp** [comment]
> Mapfish can be used as "running only when needed", right?

On my PC it tasks 5 to 7 seconds to start the container, but if we find a way to start it and keep it alive once the user has loaded the web interface, we should be fine "running it only when needed".

**Comment by nchiapol** [comment]
> @nchiapol are there options to host on the cevi server?

We could probably try to run this on the existing cevi server. However we do not have docker setup yet and in general I do not think the server can handle many more tools. So I think we should probably try to find a solution that will scale for further ideas and projects. 
Personally I think we should evaluate a second vServer and some cloud XaaS-Solutions. Besides Google and Amazone we should surely look into hosttech's offers (and probably infomaniak's). Could you start try to do some estimates there?

**Comment by wp99cp** [comment]
@nchiapol thanks for your response. 

> We could probably try to run this on the existing cevi server. However we do not have docker setup yet and in general I do not think the server can handle many more tools. So I think we should probably try to find a solution that will scale for further ideas and projects.

In this case, I would suggest that we will investigate a proper solution and don't use the existing server. In the meantime, I have an option to host it on a private vServer.

I created a team at the organisation level: https://github.com/orgs/cevi/teams/hosting-solution-for-cevi-tools

**Comment by wp99cp** [comment]
I will close this issue, has the hosting discussion is moved to the organization level and the URL choice is made.
