### ISSUE TITLE
 Translate and style file input picker

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#40]
#38 will add a web interface. This web interface has an input form file for uploading the GPX file. Currently, this field is labelled in English while all other fields are in German. We should translate this field as well.

![Screenshot from 2022-01-04 21-04-25](https://user-images.githubusercontent.com/34008738/148117161-691ad5ca-0a26-41ef-8408-5945ccdaf96c.png)

As HTML Input Form Fields are very restricted, this is not a trivial task and is therefore separated from the release of version 2.0.0 (merging of #38 into the main branch).

**Comment by wp99cp** [comment]
It's probably depending on the OS language, but I haven't tested this thesis yet,

**Comment by maede97** [comment]
I can confirm, it is dependent on the OS language. My machine is set to german, and it states "Datei auswählen" and "Keine ausgewählt".
But I guess we can keep this issue to track the work on styling.
