### ISSUE TITLE
User-Guidance

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#41]
At startup, the user should be told that the tool accepts a GPX file and nothing else. Currently it only states that we treat an "exported" tour (but does not state what that means). Only the upload dialog then specifies the GPX extension. Maybe we can also create a "tutorial" on how to export the GPX file from both SchweizMobil and SwissTopo.

**Comment by wp99cp** [comment]
I absolutely agree we should create a quick guide/tutorial on how to get such a GPX file.

**Comment by wp99cp** [comment]
The branch [feature/user-guide](https://github.com/cevi/automatic_walk-time_tables/tree/feature/user-guide) contains all preparation needed to add a user guide page. The user guide can be added to the following file: 

https://github.com/cevi/automatic_walk-time_tables/blob/da376e6e2b8b74730ffff00edc53ab09eb312d65/webinterface/src/app/pages/user-guide/user-guide.component.html#L1

**Comment by maede97** [comment]
- [ ] Todo from #51: Add sentence on why map.geo.admin.ch kml exported gpx files do not work
