### ISSUE TITLE
Compute Landeskarten on the Server

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#42]
Currently, we require a single API call to swisstopo to compute the LK numbers. This can be done on the server without the API request.

**Comment by maede97** [comment]
Can be done in the same time as #18.

**Comment by maede97** [comment]
Furthermore, some GPX/KML files return no maps. I guess the query is not run properly. Can be fixed in the same patch as this change here.

**Comment by maede97** [comment]
Furthermore, some GPX/KML files return no maps. I guess the query is not run properly. Can be fixed in the same patch as this change here.

**Comment by wp99cp** [comment]
> Currently, we require a single API call to swisstopo to compute the LK numbers. This can be done on the server without the API request.

Implemented with 16e81d6f67c57230c3d2a27fb8540aa1b0975469:
Whereas the map number query used to take up to 5 seconds, the map numbers can now be retrieved in less than 0.05s.
