### ISSUE TITLE
Add Option to Generate QR Codes for Swisstopo APP

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#422]
It would be cool to print a small QR Code on the map PDFs that can be used to load the printed tour into the Swisstopo App.

This is relatively easy and described here:
https://www.swisstopo.admin.ch/de/qr-codes-fuer-touren

**Prerequisites:**
- Store routes on our server, see also ideas in #358

**Comment by maede97** [comment]
Some initial work done: https://github.com/cevi/automatic_walk-time_tables/tree/feature/qr-code
