### ISSUE TITLE
Discussion: Route Storing

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#458]
This issue should help us track several possibilities on how to tackle route storing (#457 )

- Idea 1: Docker container with (mongo?) db and one with a simple API to store & retrieve routes & settings
  and https://github.com/mongo-express/mongo-express for viewing (on local-dev only)
- Idea 2: firebase

**Comment by wp99cp** [comment]
The big question is, what kind of data do we need to store?

## Data That Needs to be Stored:
- [ ] some id or hash that indicates the route --> can then be used to retrieve the data via URL
- [ ] encoded path (string)
- [ ] encoded waypoints (string)
- [ ] additional metadata per waypoint (to be future-proven, e.g., duration of a break at that waypoint, colour, etc.)
- [ ] creation and modification date

Anything else?

**Comment by wp99cp** [comment]
I would argue against using Firebase; it's a nice solution and would (potentially) fit our use case; however, setting up a local dev system is a pain... Also for automated testing.

**Comment by maede97** [comment]
then, I propose something like "https://map.cevi.tools/recreate/<UUID>" which will recreate the export and create a new zip
or, for QR codes: "https://map.cevi.tools/gpx/<UUID>".

**Comment by maede97** [comment]
I would tend to use the same UUID we already use to get states and logs. This makes it much easier to generate the buttons for sharing in the frontend (and generating the QR code)
