### ISSUE TITLE
Downloaded PDF file is Corrupt 

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#46]
Sometimes the created PDF is corrupt. In those cases, the PDF file is just `72 bytes` big (therefore can be considered empty).

## Reproducing
At the moment, I can't reproduce the bug systematically. While exporting _the same_ route repeatedly (with or without reloading or even restarting the docker container), the bug sometimes occurs, sometimes not.

## Debugging Approach
We can debug this problem by binding a volume to the backend container's `./output/` directory. We can accomplish this by modifying the corresponding [docker-compose.yml](https://github.com/cevi/automatic_walk-time_tables/blob/439b39ad84fa98753220120820913e63c892dae7/docker-compose.yml) file by adding;

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 2325c9e..c7c8422 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -10,6 +10,8 @@ services:
   backend:
     build:
       context: python_program/.
+    volumes:
+      - /path/to/a/local/folder:/app/output
     ports:
       - "5000:5000"
     depends_on:

```

Through that approach, I could exclude that the bug is caused by a race condition with the deleting operation as the PDFs stored in the output folder are already corrupted:
https://github.com/cevi/automatic_walk-time_tables/blob/439b39ad84fa98753220120820913e63c892dae7/python_program/app.py#L141-L143 

Therefore, the bug probably lies somewhere between the backend and mapfish or inside mapfish itself. Not within the communication between front- and backend. Nevertheless, mapfish logs the map creations as successful.

## Possible Dirty Fix
I have no measurement of how often the bug appears, but in my feeling quite often. A dirty fix would be to check the PDF site and re-fetch the PDF from mapfish if corrupted.

**Comment by maede97** [comment]
The PDF actually contains raw text:
![image](https://user-images.githubusercontent.com/14098502/149618576-53c07cb8-9201-4b45-9638-3bc6e0c87039.png)

**Comment by maede97** [comment]
https://github.com/mapfish/mapfish-print/blob/master/core/src/main/java/org/mapfish/print/servlet/MapPrinterServlet.java#L551

**Comment by wp99cp** [comment]
5b3b07530957ea5bfccce27c8ba6a7f7f53ca151 and 2b6cb8162a15942656b545c51d4bd4a60f271008 should fix this bug.

The problem was caused by a race condition in the status check. The loop queries the API as long as 'status' == 'running'. But if the first API call is dispatched too fast after the submission of the job, then 'status' is still 'waiting', therefore the loop was skipped.
https://github.com/cevi/automatic_walk-time_tables/blob/b933910de9bac826e7697a1279585435b0b87798/python_program/automatic_walk_time_tables/map_downloader/create_map.py#L155

On top of that, line 166 does not properly check if the PDF creation was successful. 
https://github.com/cevi/automatic_walk-time_tables/blob/b933910de9bac826e7697a1279585435b0b87798/python_program/automatic_walk_time_tables/map_downloader/create_map.py#L166
