### ISSUE TITLE
Enhancement: CI

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#55]
We can make use of Github CI to check for:
- codestyle (PEP 8)
- type errors / linting
- ...

**Comment by RishiKumarRay** [comment]
can we use clang format with python files?

**Comment by RishiKumarRay** [comment]
So we have to implement the above ? pycodestyle only right?

**Comment by maede97** [comment]
See #73.

**Comment by wp99cp** [comment]
I think this is independent of #73, we should add linting anyway

**Comment by maede97** [comment]
https://black.readthedocs.io/en/stable/integrations/github_actions.html
