### ISSUE TITLE
Rendering von .gpx schlägt fehl

### ISSUE THREAD

**Issue by carlobeltrame** [cevi/automatic_walk-time_tables#66]
Auf einem Firefox 99.0.1 auf Windows auf einem Microsoft Surface kann die MZB nicht generiert werden. Es ist nicht meins, darum der Screenshot mit Handy...
![DSC_0447](https://user-images.githubusercontent.com/7566995/163664077-d1599e8e-0d50-4067-a6b1-052fda8d381a.JPG)

Das Problem trat bisher auf diesem Gerät mit allen (2) .gpx-Dateien auf, die hochgeladen wurden, aber hier ein Beispiel:
https://www.dropbox.com/s/mlmo2p8xsnbvjto/Kursleiter%2002.03.2022.gpx?dl=0

Mit dieser Datei klappt es auch auf meinem Firefox 99.0 auf Ubuntu nicht. Die .gpx-Datei stammt von https://map.wanderland.ch. Dort hat man die Option, die Anzahl Punkte kann man auswählen "bis 250 Punkte" "bis 500", "bis 1000", "über 1000 Punkte". Zwei dieser Optionen wurden bereits probiert, beide haben nicht geklappt.

Die Route führt für eine kurze Strecke weg von den regulären Wanderwegen, vielleicht liegts auch daran.

**Comment by wp99cp** [comment]
Danke für dein Issue!

Ich kann das Problem bei mir local reproduzieren und werde mich um eine schnelle Fehlerbehebung bemühen.

```
backend_1       | [Level 200] [uuid=5328ee4bb2634bd18255f7a617ef5205] Der Export ist fehlgeschlagen. Ein unbekannter Fehler ist aufgetreten!
backend_1       | Exception in thread Thread-2:
backend_1       | Traceback (most recent call last):
backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
backend_1       |     self.run()
backend_1       |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
backend_1       |     self._target(*self._args, **self._kwargs)
backend_1       |   File "/app/app.py", line 41, in create_export
backend_1       |     generator.run()
backend_1       |   File "/app/automatic_walk_time_tables/generator.py", line 50, in run
backend_1       |     map_numbers = find_map_numbers(self.path_)  # map numbers and their names as a single string
backend_1       |   File "/app/automatic_walk_time_tables/geo_processing/map_numbers.py", line 60, in find_map_numbers
backend_1       |     return ",".join(sorted(maps_list, key=sort_maps))
backend_1       |   File "/app/automatic_walk_time_tables/geo_processing/map_numbers.py", line 26, in sort_maps
backend_1       |     return int(s.split("(")[1].split(")")[0].split("LK ")[1].split("/")[0])
backend_1       | IndexError: list index out of range
```

**Comment by wp99cp** [comment]
@maede97 
Das Problem liegt beim Abfragen der Landeskartennummern, #42  sollte das Issue entgültig lösen. In der Zwischenzeit werde ich einen Fix implementieren. Es scheint, als ob die API verschiedene Responsformate zurückgibt:

```
Gemmi (LK 1267)
```

oder 

```
 Chasseral (CN 1125)
```

**Comment by wp99cp** [comment]
@carlobeltrame the issue is fixed. The fix is live with version 2.2.2

**Comment by carlobeltrame** [comment]
Danke vielmals für den schnellen Fix! Ich kann bestätigen dass es jetzt funktioniert.
