### ISSUE TITLE
Add Automated Tests

### ISSUE THREAD

**Issue by wp99cp** [cevi/automatic_walk-time_tables#73]
Add automated tests before merging into the master branch.

## Things to test:
- [ ] Full stack test including user interface using cypress, puppeteer or similar framework
- [ ] Test GPX/KML parsing
- [ ] ...

**Comment by maede97** [comment]
See e.g.
- https://www.cypress.io/ which is free (for 3 users)

**Comment by maede97** [comment]
See https://github.com/maede97/automatic_walk-time_tables/tree/ci-tests
