### ISSUE TITLE
Output Map

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#8]
Let the user specify at which scale he wants the output hike trail image be generated. Currently, this is only a single image. This could potentially be changed that the user can choose the scaling (like 1:10'000) and the tool creates all maps with this zoom level (maybe use the print service to create PDF's like in the web version)

**Comment by wp99cp** [comment]
Nice would be to add this feature as a command-line option. Maybe combined with an option for defining the input file name as well as for the output directory.

**Comment by wp99cp** [comment]
See https://github.com/cevi/automatic_walk-time_tables/tree/feature/pdf-map-export for a basic MapFish setup.

**Comment by wp99cp** [comment]
Map rotation will be moved to #20
