### ISSUE TITLE
Create pip package

### ISSUE THREAD

**Issue by maede97** [cevi/automatic_walk-time_tables#9]
Requires a setup file, potentially a slightly different folder structure?
This will then benefit that this package can easily be installed and used.

**Comment by maede97** [comment]
Since we are now in a docker environment, I think we should not follow this path anymore?

**Comment by wp99cp** [comment]
I'm open to discussing this point, technically it should still be possible to run it as an independent python script: See [README.md](https://github.com/cevi/automatic_walk-time_tables/blob/dev/python_program/Readme.md).

**Comment by wp99cp** [comment]
As we now focus on the web interface we can close this issue.
