### ISSUE TITLE
Printing maps is broken

### ISSUE THREAD

**Issue by carlobeltrame** [cevi/automatic_walk-time_tables#95]
Hey! Very cool to see how this tool improves so quickly.
Currently, map generation seems to be broken. The track is rendered, but no background map is in the PDFs. I am using the following GPX track: 
[02 Route.zip](https://github.com/cevi/automatic_walk-time_tables/files/9480984/02.Route.zip)
I am leaving all settings at their defaults, only change the author name and the start date.
The following zip with useless map PDFs is downloaded: 
[Download(3).zip](https://github.com/cevi/automatic_walk-time_tables/files/9480991/Download.3.zip)

I also tried using the "Minimale Karte", did not make a difference.

**Comment by wp99cp** [comment]
Thanks for pointing it out!
I can confirm that the map export is not working currently.

**Comment by maede97** [comment]
The PDF generation works again. Thanks @carlobeltrame for pointing out the error.
